[project]
name = "localization-server"
version = "0.1.0"
description = "A simple server to host localizations in test environment."
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "fastapi>=0.115.6",
    "uvicorn>=0.34.0",
    "watchfiles>=1.0.3",
]
